language: php

php:
  - 8.0
  - 8.1
  - 8.2

os:   linux
dist: bionic

env:
  - PHALCON_VERSION="5.1.4"

git:
  depth: 1

install:
  - travis_retry composer update --no-interaction --no-progress

script:
  - vendor/bin/codecept run
  - vendor/bin/phpcs src/ --standard=psr2

notifications:
  email:
    - sid@sidroberts.co.uk
